version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app # Mount the entire 'api' folder to '/app' in the container
      - /app/node_modules # Ensures Docker ignores the host's 'node_modules'
  myblog:
    build: ./myblog
    container_name: myblog_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
